python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp5358.efp a_100.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp1174.efp a_139.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp1306.efp a_147.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn6132.efp a_148.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn3539.efp a_149.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp2319.efp a_150.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp2570.efp a_153.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala2764.efp a_161.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn5945.efp a_169.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/arg/arg05302.efp a_173.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp6393.efp a_174.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala6749.efp a_181.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn4485.efp a_198.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn7869.efp a_201.inp -d -xr
gms_slurm -p 20 -q standby -w 00:30:00 -test a_214.inp
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/arg/arg00233.efp a_216.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala6027.efp a_39.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp6156.efp a_40.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp5009.efp a_42.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala6027.efp a_61.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp1205.efp a_68.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn2035.efp a_72.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala2431.efp a_78.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp4214.efp a_79.inp -d -xr
gms_slurm -p 20 -q standby -w 00:30:00 -test a_850.inp
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asp/asp1752.efp a_852.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ala/ala0434.efp a_853.inp -d -xr
gms_slurm -p 20 -q standby -w 00:30:00 -test a_855.inp
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/arg/arg08197.efp a_856.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn3784.efp a_857.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/asn/asn7100.efp a_860.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/cys/cys0534.efp c_41.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu2969.efp g_108.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly1673.efp g_109.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu8210.efp g_156.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly3356.efp g_157.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly1554.efp g_163.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly5219.efp g_179.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gln/gln3898.efp g_190.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu0483.efp g_196.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly5454.efp g_199.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu6910.efp g_203.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly8955.efp g_205.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly4876.efp g_208.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly6236.efp g_211.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu7790.efp g_64.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu7948.efp g_77.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gln/gln4457.efp g_865.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly4479.efp g_866.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly1513.efp g_92.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/glu/glu0712.efp g_93.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly6197.efp g_94.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly6093.efp g_955.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/gly/gly5505.efp g_99.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/hid/hid1130.efp h_138.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/hid/hid2584.efp h_219.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile3822.efp i_140.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile6929.efp i_152.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile6315.efp i_162.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile5658.efp i_172.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile4504.efp i_178.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile3971.efp i_192.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile5401.efp i_195.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile4202.efp i_59.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile1981.efp i_66.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile6673.efp i_76.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile5013.efp i_80.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ile/ile1851.efp i_862.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu2105.efp l_141.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/lys/lys4519.efp l_143.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu0887.efp l_146.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu3942.efp l_151.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/lys/lys5271.efp l_160.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu7658.efp l_185.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu2137.efp l_200.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/lys/lys0326.efp l_207.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu1090.efp l_36.inp -d -xr
gms_slurm -p 20 -q standby -w 00:30:00 -test l_71.inp
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/lys/lys4606.efp l_73.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/leu/leu4727.efp l_74.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/met/met2029.efp m_864.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/met/met0067.efp m_95.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/hid/hid0643.efp opt-h_103.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/met/met1921.efp opt-m_142.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val07365.efp opt-v_144.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe5706.efp p_101.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe1696.efp p_105.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe4280.efp p_107.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/pro/pro2234.efp p_145.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe5741.efp p_168.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe3095.efp p_175.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe6318.efp p_177.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/pro/pro2289.efp p_180.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe3340.efp p_182.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/pro/pro0665.efp p_209.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe3935.efp p_217.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe0436.efp p_250.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe2471.efp p_63.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/phe/phe6504.efp p_847.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/pro/pro1563.efp p_859.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/pro/pro2622.efp p_861.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser4008.efp s_102.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser6001.efp s_106.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser0635.efp s_110.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser1402.efp s_164.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser1384.efp s_193.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser2870.efp s_204.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser2646.efp s_213.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser0030.efp s_218.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser7599.efp s_60.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser0039.efp s_65.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser7451.efp s_69.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser7044.efp s_851.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser5657.efp s_90.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser6311.efp s_954.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/ser/ser4908.efp s_97.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr2532.efp t_104.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr2338.efp t_154.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/trp/trp2559.efp t_155.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr1584.efp t_158.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/trp/trp2675.efp t_171.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/trp/trp2269.efp t_176.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr0067.efp t_202.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/trp/trp2392.efp t_215.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr2614.efp t_70.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/thr/thr1226.efp t_75.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/tyr/tyr3318.efp t_848.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/tyr/tyr1842.efp t_849.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/tyr/tyr2170.efp t_863.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val05602.efp v_111.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val10028.efp v_159.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val08299.efp v_197.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val00479.efp v_210.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val05121.efp v_212.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val05633.efp v_43.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val02098.efp v_62.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val08614.efp v_67.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val03984.efp v_854.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val05563.efp v_858.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val09273.efp v_91.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val08403.efp v_96.inp -d -xr
python step4.Flexible_V5.py /group/lslipche/data/yb_boss/flexible_efp/efpdb/val/val05402.efp v_98.inp -d -xr
rm -f ~/scr/*.script
